method: grid  #  "grid" or "random" â€” hyperparameter search method
metric:
  name: val_accuracy  # wandb.log metric
  goal: maximize

parameters:
######################################### Required for ViT
  window_size:
    values: [7,9]
  layer_norm_eps:
    values: [1e-5 , 1e-6]
  attention_probs_dropout_prob:
    values: [0]
  drop_path_rate:
   values: [0.1]
  encoder_stride:
    values: [ 16,32]
  hidden_size:
    values: [600,768]
  embed_dim : 
    value : 96
  mlp_ratio : 
    value : 4 # default 4

  depths : 
    value : [1,1,3,1] # default 2,2,6,2

  

######################################### Required for CNN
  fc1:
    value: 128
  fc2:
    value: 256
######################################### Required for Both

  epoch:
    value : 40
  bs:
    value : 32
  dropout:
      values : [0.2]
  learning_rate:
    values: [7e-6,8e-6]
  end_learning_rate: 
    value : 0.2 # Fraction of the learning rate to reach at the end of the epochs
  muon_lr: 
    value : 2.5e-4 
